#CRIE UM ALGORITMO QUE LEIA UM NUMERO E MOSTRE O SEU DOBRO, TRIPLO E RAIZ QUADADA

print('DOBRO, TRIPLO E RAIZ QUADRADA')
num = int(input('DIGITE UM NUMERO: '))
print('O SEU DOBRO É: {}\nO SEU TRIPLO É: {}\nSUA RAIZ QUADRADA É: {}'.format(num*2,num*3,num**2))
